#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'getTotalX' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def getTotalX(a, b):
    i=max(a)
    l=[]
    while(i<=min(b)):
        for j in range(0,n):
            if(i%a[j]==0):
                c=1
            else:
                c=0
                break
        if(c==1):
            l.append(i)
        i=i+1
    new=[]
    for i in range (0,len(l)):
        for j in range (0,m):
            if(b[j]%l[i]==0):
                c=1
            else:
                c=0
                break
        if(c==1):
            new.append(l[i])
    return (len(new))
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    arr = list(map(int, input().rstrip().split()))

    brr = list(map(int, input().rstrip().split()))

    total = getTotalX(arr, brr)

    fptr.write(str(total) + '\n')

    fptr.close()
