#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the equalizeArray function below.
def equalizeArray(arr):
    count=0
    for x in range(0,len(arr)):
        c=0
        for y in range (0,len(arr)):
            if(arr[x]==arr[y]):
                c+=1
        if(c>count):
            count=c
    l=len(arr)-count
    return l

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = equalizeArray(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
