#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c):
    co=0
    k=0
    while(k!=-1):
        if(((len(c)-2)-k)>2):
            if(c[k]==0 and c[k+2]==0 and c[k+2]!=2):
                co=co+1
                k=k+2
            elif (c[k]==1 and c[k]!=2):
                k=k+1
            elif(c[k]==0 and c[k+2]==1 and c[k+2]!=2):
                co=co+1
                k=k+1
        elif(((len(c)-2)-k)==2):
            co+=1
            k=-1
            break
        elif(((len(c)-2)-k)==1):
            break
    return co
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    c = list(map(int, input().rstrip().split()))
    c.append(2)
    c.append(2)
    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
