#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    m=0
    for x in range(0,n):
        l=[]
        l.append(a[x])
        for y in range(0,n):
            c=0
            k=0
            while(k<len(l)):
                if(abs(l[k]-a[y])<=1):
                    c=1
                else:
                    c=0
                    break
                k=k+1
            if(c==1):
                l.append(a[y])
        p=len(l)-1
        if(p>m):
            m=p
    return m
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
